version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  backend:
    build:
      context: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env   # 👈 carga todas las variables del archivo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # 👈 fuerza que se pase la API key
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "5555:5555"
    environment:
      - NODE_ENV=production
